Lambda-School-Labs/niyon-be

.gitignore
.idea/.gitignore
.idea/misc.xml
.idea/modules.xml
.idea/niyon-be.iml
.idea/vcs.xml
package-lock.json
package.json

Fixes # (issue)
Please delete options that are not relevant.

added inital dep

---

tests/index.js

Co-authored-by: joe joe.thompson3696@gmail.com
Co-authored-by: tim tim.mitzen@gmail.com

added test folder

---

db/seeds/00_cleanup.js
knexfile.js

Co-authored-by: Joe Thompson <joe.thompson3696@gmail.com>

Setup postgres

---

.idea/dictionaries/joe.xml
AuthRouter/AuthRouter.js
Middleware/restricted.js
package-lock.json
package.json
server.js

tearing down graphql and using express for a rest api

---

Middleware/restricted.js

Add restricted middleware

---

Routers/AuthRouter/AuthRouter.js
knexfile.js
package.json

Co-authored-by: Tim Mitzen
Co-authored-by: Joe Thompson
Checking for null on entered email in registration
Created a production environment 
Updated build script with production path

Feature email null jt/tm

---

package.json

Co-authored-by Joe Thompson <bmo3696@gmail.com>
Co-authored-by Tim Mitzen <tim.mitzen@gmail.com>

Added engine

---

.codeclimate.yml
.github/workflows/ci.yml
package.json

```Added codeclimate.yml file
Modified Package.json file for test coverages
Added git work flow folder```

Feature setup coverage

---

Routers/ProfileRouter/ProfilePackage.js
server.js
tests/middleware/restricted.test.js
tests/routes/profile.test.js

More test and fixed some other tests

---

db/test/seeds/04_user.js
tests/routes/profile.test.js

Got profile test working, all but post for profilepackage/:id

---

tests/routes/profile.test.js

deleted a non working test

---

Routers/ProfileRouter/ProfilePackage.js
documentation/README.md

deleted PUT request, created an allUsers Route, updated README

---

tests/routes/profile.test.js

fixed a test

---

knexfile.js

Co-authored-by: Time Mitzen <tim.mitzen@gmail.com>

updated knexfile to use null as default

---

knexfile.js
package.json
tests/routes/connection.test.js

Went back to local

---

Routers/ProfileRouter/ProfilePackage.js

Co-authored-by: Time Mitzen <tim.mitzen@gmail.com>

updated the profile by id to return tech as array of ids

---

README.md

Created documentation through postman
Created a shield that acts as a link to post man docs

added postman doc shield and link

---

Routers/ProfileRouter/ProfilePackage.js
db/migrations/20200607203518_stackoverflow.js

updated get profile route data return structure

---

Routers/NewsRouter/NewsRouter.js
utils/helperFunctions.js

created axios helper function for news feed calls

---

README.md
Routers/NewsRouter/NewsRouter.js
utils/helperFunctions.js

1 ) Updated the news routes to return a better format for the FE
2 ) Updated the README.md file to include the routes for news and news by topic

Feature added comments jt
